### ISSUE TITLE
Goroutine might hang around forever 

### ISSUE THREAD

**Issue by paradoxe** [sahilm/shouter#1]
The scan goroutine might hang around forever if the deadline is reached before the scan is complete.

https://github.com/sahilm/shouter/blob/cc64c6d2858ce9fefe3a09695f5c472d279ae954/server.go#L77

The solution would be to to make the 'sc' channel buffered with space for 1 value, allowing the scan goroutine to send to the channel and then exit in any case.

`sc := make(chan bool, 1)`

**Comment by sahilm** [comment]
Thanks!
